[tool.poetry]
name = "grcpPkg"
version = "0.1.0"
description = ""
authors = ["Daniel Marchena Parreira <danielmapar@gmail.com>"]

[tool.poetry.dev-dependencies]
grpcio-tools = "1.39.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
